### ISSUE TITLE
Feature Request: Facebook Reviews

### ISSUE THREAD

**Issue by chrisandy** [749/modx_facebook_feed#15]
Is it possible that this could work with Facebook reviews?

**Comment by 749** [comment]
I am afraid that it will require a lot of work to implement this, as I would need a page access token to read the reviews. In order to aquire this I will need to implement a complete Facebook login module for this plugin.
I am very sorry but currently I do not have the necessary time to implement this.

**Comment by chrisandy** [comment]
Thank you for letting me know - much appreciated
