### ISSUE TITLE
Not showing all posts

### ISSUE THREAD

**Issue by mdehaan** [749/modx_facebook_feed#7]
I can't narrow this problem down and have tested with adding and deleting multiple type's of content.
We created a page with all kinds of content (video''s, events, photogallery...), but it just shows the first 2 most recent posts. I can't get a handle on it.

**Comment by 749** [comment]
Currently only posts with a picture will be displayed, I will look into adding more post types in the future

**Comment by 749** [comment]
Posts are currently ignored if they do not have a either a description or a message, this is done so that the auto-generated post from facebook (called stories) are not displayed
I can of course pull in the url of the video or add additional fields from facebook, please let me know which field you would like to be available.
for reference see https://developers.facebook.com/docs/graph-api/reference/v2.8/post

**Comment by 749** [comment]
For some reason facebook does not include reposts in the feed of a page, I have sent them a support request asking how to access these posts.
